extension/src/manifest.json
Reverts grey-software/toonin#34
=> Revert "fixing css bug by changing how we inject, only to chrome extension an…"

.circleci/config.yml
#85 
Release zip now pushed to github after successful build of extension on CircleCI.
=> Circlecifix

.circleci/config.yml, extension/package-lock.json, extension/package.json
fixed dependency venerability error and circleci build break.
=> Dependencies

client-redesign/src/main.js, extension/src/App.vue, extension/src/app.js, extension/src/js/background/index.js
=> fixed sharing state bug and reduced transition time for reopening extension

backend/index.js, client-redesign/src/components/roomName.vue, extension/src/js/background/index.js
only rtc connection state is now being monitored for changes.
@Lakshya2610 backend and client should be updated to reflect these changes.
#100
=> fixed how handling of disconnect was implemented 

client-redesign/src/App.vue
Using localstorage to make dark mode persistent if toggled by user. Fixes #104
=> Made dark mode persistent

.circleci/config.yml, extension/package.json, setup.sh
build and dev sounded like better names to me than develop and develop:watch
=> Changed npm script names for extension

README.md, setup.sh
I made a few small updates to our README and the setup script.
=> Updated README and setup.sh

extension/src/manifest.json
Updated manifest version to 0.3
=> Version update

backend/index.js, extension/src/js/background/index.js
=> fixed rooms not being deleted on backend bug

client/src/components/ConnectToRoom.vue, client/src/components/PlayerControls.vue
=> Refactored player component to have a more pleasant UI

backend/cloud config/main.tf, client/server.js
Vue App now redirects http requests to https automatically
=> HTTP to HTTPS Automatic Redirect

README.md
Changed link from toonin.ml to www.toonin.ml. DNS doesn't resolve toonin.ml. Only app.toonin.ml & www.toonin.ml work
=> Fixed incorrect link on icon

client/src/views/Home.vue
Fixes #154 
Used Date class to retrieve current year when app is mounted. This way, we won't have to update year every year
=> fixed date on footer

backend/NetworkTree.js, client/src/main.js, deployment/NetworkTree.js, deployment/server.js, extension/src/js/background/index.js
=> Fixed issue #160 and some bugs in distributed streaming introduced after last PR

deployment/server.js
=> Updated deployment with peer count fix

app/src/layouts/MainLayout.vue
Addresses one of the points from [this issue](https://github.com/grey-software/toonin/issues/190)'s checklist.
=> Disabled the Share tab on mobile devices

.circleci/config.yml, .gitignore, packages/app/src/components/ConnectToRoom.vue, packages/app/src/components/ScreenCap.vue, packages/app/src/host.js, packages/app/src/layouts/MainLayout.vue, packages/server/RoomManager.js, packages/server/package-lock.json, packages/server/package.json, packages/server/server.js
`If (password set by host) {
server will send client a request to send password;
change to password input on client;
either cancel or respond with password;
}`
Password hash saved in Room object using bcrypt.
=> room authication added, working as expected

package-lock.json, package.json, packages/app/package-lock.json, packages/app/quasar.conf.js, packages/app/src/boot/vue-audio-visual.js, packages/app/src/components/AudioPlayer.vue, packages/app/src/components/VideoPlayer.vue, packages/app/src/pages/TooninPage.vue, packages/server/package-lock.json
=> Added an AudioPlayer component for audio only streams

packages/app/package-lock.json, packages/app/src/index.template.html, packages/server/package-lock.json
I'm setting this up to track user journeys and crashes so we can get solid data to iterate on software dev with.
=> Setup matomo analytics

packages/app/src/components/AudioPlayer.vue, packages/app/src/components/ConnectToRoom.vue, packages/app/src/components/VideoPlayer.vue, packages/app/src/layouts/MainLayout.vue, packages/app/src/pages/SharePage.vue, packages/app/src/pages/TooninPage.vue
=> Make Toonin responsive on mobile devices

packages/server/RoomManager.js, packages/server/logger.js, packages/server/package-lock.json, packages/server/package.json, packages/server/server.js
This change introduces winston as a logging library, and contains minor refactors around server.js
=> Refactored the server package's logging

packages/app/src/pages/SharePage.vue
- Removed getUserAudio
- Removed getUserVideo
- Removed the mobile check for getUserMedia since the SharePage doesn't shwo up on mobile
=> Cleaned up the Share Page's code

packages/app/src/App.vue
Toonin is developed and tested on Google chrome's desktop and mobile browser. Before we start testing on more browsers, we'll add a modal to notify users that the optimum experience is on Google Chrome.
=> Added browser check for chrome

packages/app/src/App.vue, packages/app/src/components/ConnectToRoom.vue, packages/app/src/components/ConnectionStatusTimeline.vue, packages/app/src/pages/SharePage.vue, packages/app/src/store/index.js
This change tracks a user journey using Matomo analytics' getVisitorId() function.
=> Setup user journey tracking on the web app

Dockerfile, packages/app/src/App.vue, packages/app/src/components/ConnectToRoom.vue, packages/app/src/components/ConnectionStatusTimeline.vue, packages/app/src/index.template.html, packages/app/src/pages/SharePage.vue, packages/app/src/store/index.js
This change removes all paq tracking code to bring Toonin back to a functioning state.
=> Removed paq tracking code

packages/app/src/index.template.html
This change modifies the plausible analytics domain to toonin.grey.software
=> Change domain for plausible analytics
